name: CI

on: 
  push:
    branches:
      - master
      - staging

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check whether Script runs
      run: echo Hello, world!!
    - name: Update npm to latest version
      run: npm install -g npm@latest
    - name: Install Dependencies
      run: npm install
    - name: Checking the format
      run: npm run format
    - name: Run testcases
      run: npm run test
    - name: Build application
      run: npm run build
