name: CI

on: 
  push:
    branches:
      - master
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check whether Script runs
      run: echo Hello, world!!
    - name: Install Dependencies
      run: npm install
    - name: Build application
      run: npm run build
