name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check whether Script runs
      run: echo Hello, world!!
    - name: Install Dependencies
      run: npm install
    - name: Format code
      run: npm run format
    - name: Build application
      run: npm run build
